### ISSUE TITLE
Cannot set read only property with `camera set`

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t-camera#1]
```
MeerK40t crash log. Version: 0.7.1 on win32
Traceback (most recent call last):
  File "meerk40t\gui\panes\consolepanel.py", line 117, in on_entry
  File "meerk40t\kernel.py", line 135, in __call__
  File "meerk40t\kernel.py", line 1791, in console
  File "meerk40t\kernel.py", line 1877, in _console_parse
  File "meerk40t\kernel.py", line 1230, in inner
  File "camera\camera.py", line 184, in set_camera
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-hi4qs98u\opencv\modules\videoio\src\cap.cpp:413: error: (-2:Unspecified error) in function 'bool __thiscall cv::VideoCapture::set(int,double)'
> Can't set read-only property (expected: 'propId != (int)CAP_PROP_BACKEND'), where
>     'propId' is 42
> must be not equal to
>     '(int)CAP_PROP_BACKEND' is 42

```

**Comment by tatarize** [comment]
Fixed in 0.1.7 of camera.
